=begin
originstamp.org API

Trusted Timestamp via Bitcoin blockchain

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

class InitTables < ActiveRecord::Migration
  def change
    create_table :api_key, id: false do |t|
      t.string :access_token
      t.string :name
      t.datetime :expires_at
      t.datetime :created_at
      t.datetime :updated_at
      t.integer :used

      t.timestamps
    end

    create_table :blockchain_transaction, id: false do |t|
      t.string :tx_hash
      t.string :recipient
      t.integer :status
      t.datetime :created_at
      t.datetime :updated_at
      t.string :wallet_id
      t.string :private_key
      t.string :public_key
      t.string :seed

      t.timestamps
    end

    create_table :error, id: false do |t|
      t.integer :code
      t.string :message
      t.string :fields

      t.timestamps
    end

    create_table :stamp, id: false do |t|
      t.string :hash_sha256
      t.string :sender_id
      t.datetime :created_at
      t.datetime :updated_at
      t.datetime :submitted_at
      t.string :blockchain_transaction_id
      t.string :title
      t.string :api_key_id

      t.timestamps
    end

    create_table :success, id: false do |t|
      t.integer :code
      t.string :message
      t.string :fields

      t.timestamps
    end

    create_table :url, id: false do |t|
      t.string :token
      t.datetime :created_at
      t.datetime :updated_at
      t.string :stamp_id

      t.timestamps
    end

    create_table :user, id: false do |t|
      t.string :email
      t.string :name
      t.datetime :created_at
      t.datetime :updated_at

      t.timestamps
    end

    create_table :wallet, id: false do |t|
      t.string :address
      t.datetime :created_at
      t.datetime :updated_at

      t.timestamps
    end

    create_table :whitelist_email, id: false do |t|
      t.string :email
      t.string :access_token
      t.datetime :created_at
      t.datetime :updated_at
      t.integer :confirmed

      t.timestamps
    end

  end
end
